version: '2'
services:
  turnero_api:  
    image: turnero-api
    container_name: turnero_api
    environment:
      NODE_ENV: production
      DB_HOST: mongodb://turnero_mongo:27017/turnero
      PORT: 3000
    command: ["./wait-for-it.sh", "turnero_mongo:27017", "--", "node", "index.js"]
  turnero_app:  
    image: turnero-app
    container_name: turnero_app
  turnero_reverse:
    image: nginx:1.19-alpine
    container_name: turnero_reverse 
    volumes:
      - ./docker/nginx-reverse.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  turnero_mongo:  
   image: mongo:4-focal
   container_name: turnero_mongo
   ports:
     - "27017:27017" 
